# Employee Turn Over - Data Cleansing

Cleaning the data interim we have

In [26]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import warnings
import joblib
warnings.filterwarnings("ignore")

In [23]:
PATH_DATA='../../data/raw/'
PATH_DATA_INTERIM='../../data/interim/'
PATH_MODEL = '../../model/iter1/'

## Get Data

In [3]:
df1 = pd.read_csv(PATH_DATA_INTERIM+'iter1_interim.csv')

In [4]:
df1

,unique_employee_ids,stillExists,companyAlias,is_train,vote_cnt,vote_avg,vote_std,vote_p50,vote_p75,votes_monday_cnt,...,vote_company_p50,vote_company_p75,comment_per_emp_avg,comment_len_per_emp_avg,comment_per_emp_p50,comment_len_per_emp_p50,gv_liked_per_emp_avg,gv_disliked_per_emp_avg,gv_liked_per_emp_p50,gv_disliked_per_emp_p50
0,512_56aec740f1ef260003e307d6,True,56aec740f1ef260003e307d6,0,4.0,2.500000,1.290994,2.5,3.25,1.0,...,4,4,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
1,-2_56aec740f1ef260003e307d6,False,56aec740f1ef260003e307d6,1,NaN,NaN,NaN,NaN,NaN,NaN,...,4,4,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
2,2_56aec740f1ef260003e307d6,True,56aec740f1ef260003e307d6,0,72.0,2.250000,1.031203,2.0,3.00,13.0,...,4,4,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
3,3_56aec740f1ef260003e307d6,True,56aec740f1ef260003e307d6,0,22.0,3.454545,0.738549,4.0,4.00,2.0,...,4,4,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
4,-4_56aec740f1ef260003e307d6,False,56aec740f1ef260003e307d6,1,NaN,NaN,NaN,NaN,NaN,NaN,...,4,4,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4764,857_58a728a0e75bda00042a3468,True,58a728a0e75bda00042a3468,1,1.0,3.000000,NaN,3.0,3.00,0.0,...,3,3,9.088889,931.844444,6.5,360.0,35.469027,10.668142,19.5,4.0
4765,858_58a728a0e75bda00042a3468,True,58a728a0e75bda00042a3468,0,1.0,3.000000,NaN,3.0,3.00,0.0,...,3,3,9.088889,931.844444,6.5,360.0,35.469027,10.668142,19.5,4.0
4766,859_58a728a0e75bda00042a3468,True,58a728a0e75bda00042a3468,1,1.0,4.000000,NaN,4.0,4.00,0.0,...,3,3,9.088889,931.844444,6.5,360.0,35.469027,10.668142,19.5,4.0
4767,17_573a0671b5ec330003add34a,True,573a0671b5ec330003add34a,1,7.0,3.571429,0.534522,4.0,4.00,2.0,...,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4768,19_573a0671b5ec330003add34a,True,573a0671b5ec330003add34a,1,1.0,4.000000,NaN,4.0,4.00,1.0,...,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Imputation

In [9]:
col_null = df1.isnull().sum()/len(df1)
col_null[col_null>0]

vote_cnt                   0.089956
vote_avg                   0.089956
vote_std                   0.185573
vote_p50                   0.089956
vote_p75                   0.089956
votes_monday_cnt           0.089956
votes_monday_avg           0.236528
votes_monday_std           0.393374
votes_monday_p50           0.236528
votes_monday_p75           0.236528
votes_friday_cnt           0.089956
votes_friday_avg           0.253722
votes_friday_std           0.388341
votes_friday_p50           0.253722
votes_friday_p75           0.253722
acpt_likes_cnt             0.341371
acpt_likes_avg             0.378486
acpt_likes_std             0.379534
acpt_likes_p50             0.378486
acpt_likes_p75             0.378486
acpt_dislikes_cnt          0.341371
acpt_dislikes_avg          0.530090
acpt_dislikes_std          0.531768
acpt_dislikes_p50          0.530090
acpt_dislikes_p75          0.530090
len_txt_cnt                0.341371
len_txt_avg                0.341371
len_txt_std                0.342210
len_txt_p50                0.341371
len_txt_p75                0.341371
comment_weekend_cnt        0.341371
comment_weekday_cnt        0.341371
comment_morning_cnt        0.341371
comment_night_cnt          0.341371
comment_lunch_cnt          0.341371
gv_liked_cnt               0.268819
gv_disliked_cnt            0.268819
reaction_cnt               0.268819
comment_per_emp_avg        0.000419
comment_len_per_emp_avg    0.000419
comment_per_emp_p50        0.000419
comment_len_per_emp_p50    0.000419
gv_liked_per_emp_avg       0.004403
gv_disliked_per_emp_avg    0.004403
gv_liked_per_emp_p50       0.004403
gv_disliked_per_emp_p50    0.004403
dtype: float64

In [11]:
df2 = df1.fillna(0)

In [12]:
df2

,unique_employee_ids,stillExists,companyAlias,is_train,vote_cnt,vote_avg,vote_std,vote_p50,vote_p75,votes_monday_cnt,...,vote_company_p50,vote_company_p75,comment_per_emp_avg,comment_len_per_emp_avg,comment_per_emp_p50,comment_len_per_emp_p50,gv_liked_per_emp_avg,gv_disliked_per_emp_avg,gv_liked_per_emp_p50,gv_disliked_per_emp_p50
0,512_56aec740f1ef260003e307d6,True,56aec740f1ef260003e307d6,0,4.0,2.500000,1.290994,2.5,3.25,1.0,...,4,4,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
1,-2_56aec740f1ef260003e307d6,False,56aec740f1ef260003e307d6,1,0.0,0.000000,0.000000,0.0,0.00,0.0,...,4,4,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
2,2_56aec740f1ef260003e307d6,True,56aec740f1ef260003e307d6,0,72.0,2.250000,1.031203,2.0,3.00,13.0,...,4,4,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
3,3_56aec740f1ef260003e307d6,True,56aec740f1ef260003e307d6,0,22.0,3.454545,0.738549,4.0,4.00,2.0,...,4,4,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
4,-4_56aec740f1ef260003e307d6,False,56aec740f1ef260003e307d6,1,0.0,0.000000,0.000000,0.0,0.00,0.0,...,4,4,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4764,857_58a728a0e75bda00042a3468,True,58a728a0e75bda00042a3468,1,1.0,3.000000,0.000000,3.0,3.00,0.0,...,3,3,9.088889,931.844444,6.5,360.0,35.469027,10.668142,19.5,4.0
4765,858_58a728a0e75bda00042a3468,True,58a728a0e75bda00042a3468,0,1.0,3.000000,0.000000,3.0,3.00,0.0,...,3,3,9.088889,931.844444,6.5,360.0,35.469027,10.668142,19.5,4.0
4766,859_58a728a0e75bda00042a3468,True,58a728a0e75bda00042a3468,1,1.0,4.000000,0.000000,4.0,4.00,0.0,...,3,3,9.088889,931.844444,6.5,360.0,35.469027,10.668142,19.5,4.0
4767,17_573a0671b5ec330003add34a,True,573a0671b5ec330003add34a,1,7.0,3.571429,0.534522,4.0,4.00,2.0,...,4,4,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0
4768,19_573a0671b5ec330003add34a,True,573a0671b5ec330003add34a,1,1.0,4.000000,0.000000,4.0,4.00,1.0,...,4,4,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0

## Outliers

In [30]:
col_out = set(df2.columns)-set(['unique_employee_ids','stillExists','companyAlias','is_train'])
df2_train = df2[df2.is_train == 1]

In [31]:
outlier_rules = df2_train[col_out].quantile(0.98).to_dict()
joblib.dump(outlier_rules, PATH_MODEL+'outliers_rules.pkl')

['../../model/iter1/outliers_rules.pkl']

In [32]:
df3 = df2.copy()
for c in col_out:
    df3[c] = np.where(df3[c]>=outlier_rules[c], outlier_rules[c], df3[c])

In [33]:
df3

,unique_employee_ids,stillExists,companyAlias,is_train,vote_cnt,vote_avg,vote_std,vote_p50,vote_p75,votes_monday_cnt,...,vote_company_p50,vote_company_p75,comment_per_emp_avg,comment_len_per_emp_avg,comment_per_emp_p50,comment_len_per_emp_p50,gv_liked_per_emp_avg,gv_disliked_per_emp_avg,gv_liked_per_emp_p50,gv_disliked_per_emp_p50
0,512_56aec740f1ef260003e307d6,True,56aec740f1ef260003e307d6,0,4.0,2.500000,1.271135,2.5,3.25,1.0,...,4.0,4.0,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
1,-2_56aec740f1ef260003e307d6,False,56aec740f1ef260003e307d6,1,0.0,0.000000,0.000000,0.0,0.00,0.0,...,4.0,4.0,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
2,2_56aec740f1ef260003e307d6,True,56aec740f1ef260003e307d6,0,72.0,2.250000,1.031203,2.0,3.00,13.0,...,4.0,4.0,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
3,3_56aec740f1ef260003e307d6,True,56aec740f1ef260003e307d6,0,22.0,3.454545,0.738549,4.0,4.00,2.0,...,4.0,4.0,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
4,-4_56aec740f1ef260003e307d6,False,56aec740f1ef260003e307d6,1,0.0,0.000000,0.000000,0.0,0.00,0.0,...,4.0,4.0,40.497238,3133.790055,24.0,1522.0,105.754902,30.171569,35.5,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4764,857_58a728a0e75bda00042a3468,True,58a728a0e75bda00042a3468,1,1.0,3.000000,0.000000,3.0,3.00,0.0,...,3.0,3.0,9.088889,931.844444,6.5,360.0,35.469027,10.668142,19.5,4.0
4765,858_58a728a0e75bda00042a3468,True,58a728a0e75bda00042a3468,0,1.0,3.000000,0.000000,3.0,3.00,0.0,...,3.0,3.0,9.088889,931.844444,6.5,360.0,35.469027,10.668142,19.5,4.0
4766,859_58a728a0e75bda00042a3468,True,58a728a0e75bda00042a3468,1,1.0,4.000000,0.000000,4.0,4.00,0.0,...,3.0,3.0,9.088889,931.844444,6.5,360.0,35.469027,10.668142,19.5,4.0
4767,17_573a0671b5ec330003add34a,True,573a0671b5ec330003add34a,1,7.0,3.571429,0.534522,4.0,4.00,2.0,...,4.0,4.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0
4768,19_573a0671b5ec330003add34a,True,573a0671b5ec330003add34a,1,1.0,4.000000,0.000000,4.0,4.00,1.0,...,4.0,4.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0

In [34]:
df3.to_csv(PATH_DATA_INTERIM+'iter1_interim_cln.csv',index = False)